### ISSUE TITLE
Not injecting

### ISSUE THREAD

**Issue by LaxmanGuy** [arturzxc/grinder#12]
Im currently looking into fixing it, I only have basic coding knowledge however but I believe it isn't built for the current version of the game but I cannot seem to figure out where I could potentially fix that

**Comment by xunyangjian1** [comment]
I ONLY HAVE BASIC CODING KNOWLEDGE

**Comment by arturzxc** [comment]
The cheat has been updated

**Comment by Puffinnop** [comment]
@arturzxc I still use this today. It’s amazing I applaud the work and time you dedicated to this. Thank you!
