### ISSUE TITLE
offsets

### ISSUE THREAD

**Issue by danytrol** [arturzxc/grinder#3]
A new patch has been released and needs to be updated again.
Waiting for a playable level! Sleeping 10 seconds... 
Waiting for a playable level! Sleeping 10 seconds... 
Waiting for a playable level! Sleeping 10 seconds...

**Comment by furfury** [comment]
!!!ERROR!!! Failed to get 4at: 4 SLEEPING 10 SECONDS AND TRYING AGAIN!
what is the fix for this?

**Comment by danytrol** [comment]
> !!! ОШИБКА!!! Не удалось получить 4at: 4 СПИТ 10 секунд И пытается СНОВА! как это исправить?

    #pragma once
     
    //ядро
    constexpr long OFF_REGION = 0x140000000;                      //[Статический]-> Регион
    constexpr long OFF_LEVEL = 0x1690670;                         //[Разное]->ИмяурОвня
    constexpr long OFF_LOCAL_PLAYER = 0x2119848;                  //[Разное]-> LocalPlayer
    constexpr long OFF_ENTITY_LIST = 0x1d6b5d8;                   //[Разное]-> cl_entitylist
     
    //кнопки
    constexpr long OFF_IN_ATTACK = 0x07383af0;                     //[Кнопки]-> in_attack
    constexpr long OFF_IN_JUMP = 0x07383bf0;                       //[Кнопки]-> in_jump
     
    // плеер
    constexpr long OFF_ZOOMING = 0x1c01;                          //[RecvTable.DT_Player]-> m_bZooming
    constexpr long OFF_LOCAL_ORIGIN = 0x0188;                     //[Карта данных.CBaseViewModel]-> m_localOrigin
    constexpr long OFF_TEAM_NUMBER = 0x037c;                      //[RecvTable.DT_BaseEntity]-> m_iTeamNum
    constexpr long OFF_CURRENT_HEALTH = 0x036c;                   //[RecvTable.DT_BaseEntity]-> m_iHealth
    constexpr long OFF_CURRENT_SHIELDS = 0x01a0;                  //[RecvTable.DT_BaseEntity]-> m_shieldHealth
    constexpr long OFF_NAME = 0x04b9;                             //[RecvTable.DT_BaseEntity]-> m_iName
    constexpr long OFF_SIGNIFIER_NAME = 0x04b0;                   //[RecvTable.DT_BaseEntity]-> m_iSignifierName
    constexpr long OFF_LIFE_STATE = 0x06c8;                       //[RecvTable.DT_Player]-> m_lifeState
    constexpr long OFF_BLEEDOUT_STATE = 0x2710;                   //[RecvTable.DT_Player]-> m_bleedoutState
    constexpr long OFF_LAST_VISIBLE_TIME = 0x19bd + 0x3;          //[RecvTable.DT_BaseCombatCharacter]->m_hudInfo_visibilityTestAlwaysPasses + 0x3
    constexpr long OFF_LAST_AIMEDAT_TIME = 0x19bd + 0x3 + 0x8;    //[RecvTable.DT_BaseCombatCharacter]->m_hudInfo_visibilityTestAlwaysPasses + 0x3 + 0x8
    constexpr long OFF_VIEW_ANGLES = 0x2564 - 0x14;               //[DataMap.C_Player]-> m_ammoPoolCapacity - 0x14
    constexpr long OFF_PUNCH_ANGLES = 0x2468;                     //[?]->m_currentFrameLocalPlayer.m_vecPunchWeapon_Angle
    //оружие
    constexpr long OFF_WEAPON_HANDLE = 0x1964;                    //[RecvTable.DT_Player]->m_latestPrimaryWeapons
    constexpr long OFF_WEAPON_INDEX = 0x17a8;                     //[RecvTable.DT_WeaponX]->m_weaponNameIndex
    //glow
    constexpr long OFF_GLOW_ENABLE = 0x294;                       //[DT_HighlightSettings].?
    constexpr long OFF_GLOW_THROUGH_WALL = 0x278;                 //[DT_HighlightSettings].?
    constexpr long OFF_GLOW_FIX = 0x270;
    constexpr long OFF_GLOW_HIGHLIGHT_ID = 0x298;                 //[DT_HighlightSettings].m_highlightServerActiveStates
    constexpr long OFF_GLOW_HIGHLIGHTS = 0xB5C5090;

**Comment by arturzxc** [comment]
Offsets updated! Respawn rolled out couple minipatches over the last 1-2 days and also EA and Steam were on different versions to compound the problem. Now all should work as usual
